# Generated by Django 4.1 on 2022-08-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijelo', models.CharField(max_length=255)),
                ('vrijeme_komentiranja', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-vrijeme_komentiranja',),
            },
        ),
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijelo', models.CharField(max_length=255)),
                ('vrijeme_stvaranja', models.DateTimeField(auto_now_add=True)),
                ('objava_komentari', models.ManyToManyField(blank=True, related_name='komentar_korisnik', through='app.Komentar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-vrijeme_stvaranja',),
            },
        ),
        migrations.CreateModel(
            name='Srce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_lajkanja', models.DateTimeField(auto_now_add=True)),
                ('objava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srca', to='app.objava')),
                ('stvorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=255)),
                ('lokacija', models.CharField(max_length=50)),
                ('datum_pridruzivanja', models.DateField(auto_now_add=True)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prati', models.ManyToManyField(blank=True, related_name='pracen_od', to='app.profil')),
            ],
        ),
        migrations.AddField(
            model_name='objava',
            name='objava_lajkovi',
            field=models.ManyToManyField(blank=True, related_name='srce_korisnik', through='app.Srce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objava',
            name='stvorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objave', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='komentar',
            name='objava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to='app.objava'),
        ),
        migrations.AddField(
            model_name='komentar',
            name='stvorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to=settings.AUTH_USER_MODEL),
        ),
    ]
